// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xplrulguxekhgeqsarkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwbHJ1bGd1eGVraGdlcXNhcmttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0OTk4MDEsImV4cCI6MjA2NDA3NTgwMX0.lSMDqJcPYOKdvdmCC1Pzr73rjhA62shGLP8IwjGFYoo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);